apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-certs
  namespace: coder # Your Coder deployment namespace
spec:
  commonName: "*.ide.1e100.one"
  dnsNames:
    - "ide.1e100.one"
    - "*.ide.1e100.one"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: coder-certs
