name: GitHub Actions Demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    # Setup worker env for build, get build tools etc
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - run: |
        nix-channel --list
        nix-env -iA nixpkgs.bazel_4 nixpkgs.automake nixpkgs.libtool nixpkgs.gcc
        nix-env --set-flag priority 0 gcc-wrapper
        nix-env -iA nixpkgs.bintoolsNoLibc nixpkgs.gnum4 nixpkgs.autoconf
    # Run a build
    - run: |
        bazel build //server:server
